lib{mytest}: libul{mytest}: {hxx ixx txx cxx}{**}

# '.def' File for Automatic DLL Symbol Exportation
#
libs{mytest}: def{mytest}: include = ($cxx.target.system == 'win32-msvc')
def{mytest}: libul{mytest}
if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{mytest}: cxx.export.poptions = "-I$out_root" "-I$src_root"

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mytest}: bin.lib.version = "-$version.project_id"
else
  lib{mytest}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmytest/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmytest/
  install.subdirs = true
}
