intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{mytest}: libul{mytest}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# '.def' File for Automatic Symbol Exportation
#
libs{mytest}: def{mytest}: include = ($cxx.target.system == 'win32-msvc')
def{mytest}: libul{mytest}

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

{hbmia obja}{*}: cxx.poptions += -DLIBMYTEST_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMYTEST_SHARED_BUILD

# Export options.
#
lib{mytest}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mytest}: cxx.export.poptions += -DLIBMYTEST_STATIC
libs{mytest}: cxx.export.poptions += -DLIBMYTEST_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mytest}: bin.lib.version = "-$version.project_id"
else
  lib{mytest}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmytest/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmytest/
  install.subdirs = true
}
